# 3. Perform the following. Create 3 pods with names nginx1, nginx2, nginx3. All of them should have the label app=v1. 
# i. Show all labels of the pods. 
# ii. Get only the 'app=v2' pods. 
# iii.	Remove the 'app' label from the pods we created before */

kubectl create namespace ms22cs107

kubectl run nginx1 --image=172.1.14.168:5001/nginx --restart=Never --labels=app=v1 --namespace=ms22cs107
kubectl run nginx2 --image=172.1.14.168:5001/nginx --restart=Never --labels=app=v1 --namespace=ms22cs107
kubectl run nginx3 --image=172.1.14.168:5001/nginx --restart=Never --labels=app=v1 --namespace=ms22cs107

# Show all labels of the pods: kubectl get po --show-labels --namespace=ms22cs107
# Get only the 'app=v2' pods: kubectl get po -l app=v2 --namespace=ms22cs107
# Remove the 'app' label from the pods we created before: kubectl label po nginx1 nginx2 nginx3 app- --namespace=ms22cs107
# Do show all labels of the pods again to make sure labels are deleted: kubectl get po --show-labels --namespace=ms22cs107
