#4.Create a Pod with ubuntu image and a command to echo “YOUR_NAME” which overrides the default CMD/ENTRYPOINT of the image. Delete pod.

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: ms22cs107
  labels:
    app: ubuntu-label

spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "echo PRATYUSH"]

# Create Namespace: kubectl create namespace ms22cs107
# Create Pod: kubectl apply -f q4.yaml --namespace=ms22cs107
# Show O/P: kubectl logs ubuntu-pod --namespace=ms22cs107
# Delete Pod: kubectl delete pod ubuntu-pod --namespace=ms22cs107
# To Confirm: kubectl get pods --namespace=ms22cs107
