# 5. Create a Pod that runs one container. 
# The configuration file for the Pod defines a command and arguments by using environment variables and then delete the pod.

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: ms22cs107
  labels:
    app: ubuntu-label

spec: 
  containers:
  - name: ubuntu-container
    image: ubuntu
    env:
    - name: message
      value: "Hello MSRIT"
    command: ["/bin/bash"]
    args: ["-c","echo $message"]

# Create Namespace: kubectl create namespace ms22cs107
# Create Pod: kubectl apply -f q5.yaml
# Check output: kubectl logs ubuntu-pod --namespace=ms22cs107
# Delete Pod: kubectl delete pod ubuntu-pod --namespace=ms22cs107
